name: Publish Package to NPM and GitHub Registry
env:
  SDK_VERSION: ${{ github.event.inputs.tag || github.event.release.tag_name || 'canary' }}
on:
  release:
    types:
      - published
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Test Package
        run: bun test
      - name: Build Package
        run: bun run build
      - name: Release
        run: bun upload-npm -- "${{ env.SDK_VERSION }}" publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
